### PR TITLE
Prepare document for release

### PR DESCRIPTION
**Pull request by timj**
@mjuric, @womullan, I'm getting the document ready for release to DocuShare.

@suberlak can you please clarify some things?

1. Where are all the figures? I only see 2 figures in the repository but `main.tex` refers to more figures and has them in a `figs` directory that is not in the repository.
2. There are preliminary reports in the repo that I assume I can delete. `2017_02_progress.tex`, `2017_03_progress.tex`, `2017_03_progress_mnras.tex` and `main_mnras.tex`.
3. The bib entries for `vanderplas2015` and `vanderplas2017` are missing.

### CODE REVIEW

**Comment by timj** [comment]
Is vanderplas2015 https://ui.adsabs.harvard.edu/#abs/2015ApJ...812...18V/abstract ?
Is vanderplas2017 https://ui.adsabs.harvard.edu/#abs/2017arXiv170309824V/abstract ?

**Comment by suberlak** [comment]
Hi!

I just added these two references to .bib file and pushed to the repository

Best wishes
Chris

**Comment by timj** [comment]
Thanks. Using this branch would have helped me a bit, as I've rewritten the bib file so have a conflict. I'll sort it out. If you've got the missing figures that would be great. The figures can go on master, I can rebase since there will be no conflict.

**Comment by suberlak** [comment]
Hi!

I am sorry I didn’t realize I did something wrong, let me know what I can do to make it better.  I asked Mario whether I should keep original figure names (which are quite descriptive), or change to something shorter (like Fig1_.., Fig2_…. ) . If this can be changed at later time I can add the figs/ directory as-is.

Best wishes
Chris

**Comment by suberlak** [comment]
Hi!

I added the entire directory as is,  let me know if I can help in any other way.

Best wishes
Chris

**Comment by timj** [comment]
Thanks. I'll have a look. Thank you so much for your quick response to this.

**Comment by timj** [comment]
Looking great now. I've made some tweaks and I'll upload to docushare tomorrow.

**Comment by suberlak** [comment]
Hi Tim!

I didn't comment on that,  but you can delete the monthly progress, those were just one-page summaries of what was done each month, 

Best wishes
Chris

**Comment by timj** [comment]
@suberlak thanks for the clarification. I'll clean them up. I left them there because they are explicitly mentioned in the main DMTR-22 report. I'll remove that sentence as well.

**Pull request merged**
